import type { Metadata } from 'next'
import { Geist, Geist_Mono, Felipa } from 'next/font/google'
import './globals.css'
import Header from '@/src/components/Header'
import Footer from '@/src/components/Footer'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})
const felipa = Felipa({ variable: '--font-felipa', subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${felipa.variable} antialiased max-w-screen-2xl mx-auto bg-neutral-200 h-screen`}
            >
                <Header title="Tekboard Blog" />
                {children}
                <Footer />
            </body>
        </html>
    )
}
